config/routes.rb
Rails.application.routes.draw do
  resources :books
  
  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
    
    has_attached_file :book_img, :path => ":rails_root/public/system/users/images/:id/:style/:filename",
     :url => "/system/users/images/:id/:style/:filename", styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
    
    # validates_attachment_content_type :book_img, :content_type => [/\Aimage\/.*\Z/, /\Avideo\/.*\Z/, /\Aaudio\/.*\Z/, /\Aapplication\/.*\Z/]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all.order("created_at DESC")
    end
    
    def new
        @book = Book.new
    end
    
    def show
        @book = Book.find(params[:id])
    end
    
    def create
        @book = Book.new(book_params)
        
        if @book.save
            redirect_to Book.last
        else
            render 'new'
        end
    end
    
    private
        def book_params
           params.require(:book).permit(:title, :description, :author, :category_id, :book_img) 
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
<%= f.file_field :book_img %>
  <%= f.input :title, label: "Book title" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
    <h1>There are no books currently in this category</h1>
<% else %>
<% @books.each do |book| %>
    <a href="/books/<%= book.id %>">
        <%= image_tag book.book_img.url(:book_index) %>
    </a>
<% end %>
<% end %>

<%= link_to "Add Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<%= image_tag @book.book_img.url(:book_show), class: "book-show" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imagepre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>